added pytest-cov

diff --git a/.github/workflows/ci_cd_wf.yml b/.github/workflows/ci_cd_wf.yml
--- a/.github/workflows/ci_cd_wf.yml
+++ b/.github/workflows/ci_cd_wf.yml
@@ -11,6 +11,9 @@ on:
 jobs:
   test:
     runs-on: ubuntu-latest
+    env:
+      COVERAGE_SINGLE: 60
+      COVERAGE_TOTAL: 60
 
     steps:
       - name: Check out repo code
@@ -27,3 +30,28 @@ jobs:
       - name: Run tests
         run: |
           python -m pytest -v tests
+      
+      - name: pytester-cov
+          id: pytester-cov
+          uses: programmingwithalex/pytester-cov@main
+          with:
+            pytest-root-dir: '.'
+            cov-threshold-single: ${{ env.COVERAGE_SINGLE }}
+            cov-threshold-total: ${{ env.COVERAGE_TOTAL }}
+
+      - name: Coverage single fail - exit
+        if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
+        run: |
+          echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-single-fail }}"
+          exit 1
+
+      - name: Coverage total fail - exit
+        if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
+        run: |
+          echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
+          exit 1
+
+      - name: Commit pytest coverage table
+        uses: peter-evans/commit-comment@main
+        with:
+          body: ${{ steps.pytester-cov.outputs.output-table }}
